name       : ricochet
version    : 1.1.2
release    : 3
source     :
    - https://ricochet.im/releases/1.1.2/ricochet-1.1.2-src.tar.bz2 : 97c78d088892e84c95a3e3a4a982883d8e44028848a513a5d7e0231d36325cc3
license    : BSD-3-Clause
component  : network.im
summary    : Anonymous metadata-resistant instant messaging that just works.
description: |
    Ricochet is an experimental kind of instant messaging that doesn't trust anyone with your identity, your contact list, or your communications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(openssl)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Svg)
rundeps    :
    - tor
setup      : |
    qmake DEFINES+=RICOCHET_NO_PORTABLE ricochet.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
