name       : ricochet
version    : 1.1.4
release    : 10
source     :
    - https://github.com/ricochet-im/ricochet/archive/v1.1.4.tar.gz : 4eb9000bc3f6c6a18659479015af980c16f971d468d10410ebeac8ada720d2cd
license    : BSD-3-Clause
component  : network.im
summary    : Anonymous metadata-resistant instant messaging that just works.
description: |
    Ricochet is an experimental kind of instant messaging that doesn't trust anyone with your identity, your contact list, or your communications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(openssl)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
rundeps    :
    - qt5-multimedia
    - qt5-quickcontrols
    - tor
setup      : |
    %qmake DEFINES+=RICOCHET_NO_PORTABLE ricochet.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
